### ISSUE TITLE
code for hsv_tester

### ISSUE THREAD

**Issue by jtpoolmania** [the-raspberry-pi-guy/raspirobots#1]
Hello- I am getting an error on line 5 import cv2 and on line 3. I was wondering if there was an update to the code. I amenjoying thebook. Thanks.

**Comment by the-raspberry-pi-guy** [comment]
Hi there! Glad you're enjoying the book.

I am not currently in a position to easily test the code at the moment - would you mind sharing some information about the error you are seeing? Screenshots and as much details as possible would be great - thanks for bringing this to my attention!

**Comment by GregoireLapert** [comment]
I think I have the same problem here. Looks like he can't import picamera and cv2.
![IMG_20200122_121949](https://user-images.githubusercontent.com/48855468/72890365-fe652000-3d11-11ea-8b67-2079130cdd7b.jpg)
I'm new to raspberry pi so it would be nice if you could help me :)

**Comment by jtpoolmania** [comment]
Hello. Yes, I believe it is the github, but I am also at a school and sometimes they change the internet filters and it might block github.

I will see if that’s the issue as I will try to the download at home next week.

Jonathan D. Taylor
Technology and Engineering Teacher
Central Bucks High School WEST
267-893-2500 xt. 7550

**Comment by sringland** [comment]
Same problem. I went through the sequence of the library installs, then I see this when I run hsv_tester.py: 

>>> %Run hsv_tester.py
Traceback (most recent call last):
  File "/home/pi/robot/hsv_tester.py", line 5, in <module>
    import cv2
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 305, in _custom_import
    module = self._original_import(*args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
  File "/usr/lib/python3/dist-packages/thonny/backend.py", line 305, in _custom_import
    module = self._original_import(*args, **kw)
ImportError: /usr/local/lib/python3.7/dist-packages/cv2/cv2.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: __atomic_fetch_add_8

**Comment by GregoireLapert** [comment]
I finally found out how to solve this problem, you have to open the linux terminal and execute the following code : 
- cd path_to_the_folder_with_the_code
- LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.sol python3 name_of_the_code.py

**Comment by the-raspberry-pi-guy** [comment]
Hi Gregoire,

Thanks for the fix with this - I have been snowed under at University and unable to try to resolve this myself. Would you be able to post also where you figured this out from? It would be good if I could do some overall reading so that I can then make an update to be included on the book's retail page, and in this GitHub repo.

My apologies for not being able to also debug. I'm hoping things will have cleared up by the weekend and then should be able to get my Pi and have a go :)

**Comment by GregoireLapert** [comment]
A coworker of mine solve this problem, I think he found it on the opencv's issues page on github. But he just came up with the solution three days after the problem was declared so I don't really know how he found the solution.

**Comment by the-raspberry-pi-guy** [comment]
Thanks for the fix - I have pinned this so others can find it :))

**Comment by jtpoolmania** [comment]
No problem! Thanks again for addressing the issue. Good luck with your studies!

Jonathan D. Taylor
Technology and Engineering Teacher
Central Bucks High School WEST
267-893-2500 xt. 7550
