### ISSUE TITLE
Code for object tracker error

### ISSUE THREAD

**Issue by Timeking1** [the-raspberry-pi-guy/raspirobots#2]
Good day , upon execution of the color tracker code , I receive this error , any help you can offer?:

"Traceback (most recent call last):
  File "/home/pi/PycharmProjects/pythonProject/ball_follow.py", line 32, in <module>
    image2, countours, hierarchy = cv2.findContours(color_mask, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)"

![Annotation 2020-08-30 142730](https://user-images.githubusercontent.com/69599862/91666707-fb62b700-eacc-11ea-90ca-ca7cf85012c7.png)

**Comment by Timeking1** [comment]
Fixed issue by removing image2, variable from line 32 in my picture

**Comment by the-raspberry-pi-guy** [comment]
Hi there,

Sorry for not spotting this earlier! Yes, looks like OpenCV has changed their API - thanks for the spot :))
